### PR TITLE
integrate bundle format changes

### PR DESCRIPTION
**Pull request by bdehamer**
#### Summary
Updates the generated bundle types to match the latest [changes](https://github.com/sigstore/protobuf-specs/pull/36/files) to the protobufs. This is a breaking change as the serialized bundle format is now different. The primary change is that the `tlogEntries` array is now part of the `verificationMaterial` object (the `verificationData` field has been removed from the bundle entirely).

Old Format:
```json
{
  "mediaType": "application/vnd.dev.sigstore.bundle+json;version=0.1",
  "verificationMaterial": {
    "x509CertificateChain": {
      "certificates": [
        {
          "rawBytes": "MIICoDCCAiWgAwIBAgIUWgawjOXEzeCMsttpLScshik+QkQwCgYIKoZIzj0EAwMwNzEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MR4wHAYDVQQDExVzaWdzdG9yZS1pbnRlcm1lZGlhdGUwHhcNMjIxMjE5MjAxNTAwWhcNMjIxMjE5MjAyNTAwWjAAMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKeMoiWnWq/TkzkR0BhjkrzSON3/bVKRR6baFaAETD5Gecu2Ii2Fh45bH1EAmlXkFc2oXYD1cDOzlCwkTOn7D9aOCAUQwggFAMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQU8J6puM9FoV9FxgiXiP6hKHVQpiAwHwYDVR0jBBgwFoAU39Ppz1YkEZb5qNjpKFWixi4YZD8wHwYDVR0RAQH/BBUwE4ERYnJpYW5AZGVoYW1lci5jb20wLAYKKwYBBAGDvzABAQQeaHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoMIGJBgorBgEEAdZ5AgQCBHsEeQB3AHUA3T0wasbHETJjGR4cmWc3AqJKXrjePK3/h4pygC8p7o4AAAGFLAZ9QwAABAMARjBEAiAinTW8WjUL/eTmBiRRcjz30Gw3WPCru2Q21cM80Tpj4QIgSggWwsVzVg9peuHtHwEAuiS8UXjKgOdOBngjUYg/5iUwCgYIKoZIzj0EAwMDaQAwZgIxAKywmGgzrnCzO+NyrFhJPB3jzY5EeQfOOVXXbTvgW/W+RvHF6k94P3iZO+dqFLWj/QIxALOubQRXtR5OcQXn9U9nPLazKo46PSigqv1aXSOlOcbRVLNLxCUfUtPA+V/Qy1hcFw=="
        },
        {
          "rawBytes": "MIICGjCCAaGgAwIBAgIUALnViVfnU0brJasmRkHrn/UnfaQwCgYIKoZIzj0EAwMwKjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0yMjA0MTMyMDA2MTVaFw0zMTEwMDUxMzU2NThaMDcxFTATBgNVBAoTDHNpZ3N0b3JlLmRldjEeMBwGA1UEAxMVc2lnc3RvcmUtaW50ZXJtZWRpYXRlMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8RVS/ysH+NOvuDZyPIZtilgUF9NlarYpAd9HP1vBBH1U5CV77LSS7s0ZiH4nE7Hv7ptS6LvvR/STk798LVgMzLlJ4HeIfF3tHSaexLcYpSASr1kS0N/RgBJz/9jWCiXno3sweTAOBgNVHQ8BAf8EBAMCAQYwEwYDVR0lBAwwCgYIKwYBBQUHAwMwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU39Ppz1YkEZb5qNjpKFWixi4YZD8wHwYDVR0jBBgwFoAUWMAeX5FFpWapesyQoZMi0CrFxfowCgYIKoZIzj0EAwMDZwAwZAIwPCsQK4DYiZYDPIaDi5HFKnfxXx6ASSVmERfsynYBiX2X6SJRnZU84/9DZdnFvvxmAjBOt6QpBlc4J/0DxvkTCqpclvziL6BCCPnjdlIB3Pu3BxsPmygUY7Ii2zbdCdliiow="
        },
        {
          "rawBytes": "MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMwKjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0yMTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3JlLmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxexX69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92jYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRYwB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQKsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCMWP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ"
        }
      ]
    },
  },
  "verificationData": {
    "tlogEntries": [
      {
        "logIndex": "9430952",
        "logId": {
          "keyId": "wNI9atQGlz+VWfO6LRygH4QUfY/8W4RFwiT5i5WRgB0="
        },
        "kindVersion": {
          "kind": "hashedrekord",
          "version": "0.0.1"
        },
        "integratedTime": "1671480901",
        "inclusionPromise": {
          "signedEntryTimestamp": "MEQCIAgWJ1fq2e9fi7LwZRzVYXFg0vFxW8zahdXIWntyMMNoAiAhaTaEJkwTLYd8qiz162u8zHETX7o5qbXK38aKd1Vmkw=="
        },
        "canonicalizedBody": "eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI2OGU2NTZiMjUxZTY3ZTgzNThiZWY4NDgzYWIwZDUxYzY2MTlmM2U3YTFhOWYwZTc1ODM4ZDQxZmYzNjhmNzI4In19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FVUNJUURaTWRXN2VodUxpWm9VTTBCWkhGa2VHZXRxY0I5WU5DZVNlT1RpZEJYYUVnSWdJdzEyMW4ySzRmbVVDN3J0cWNWSzJId0l2eFpqZnZ1SXpBa2VQTVhMYkU0PSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTnZSRU5EUVdsWFowRjNTVUpCWjBsVlYyZGhkMnBQV0VWNlpVTk5jM1IwY0V4VFkzTm9hV3NyVVd0UmQwTm5XVWxMYjFwSmVtb3dSVUYzVFhjS1RucEZWazFDVFVkQk1WVkZRMmhOVFdNeWJHNWpNMUoyWTIxVmRWcEhWakpOVWpSM1NFRlpSRlpSVVVSRmVGWjZZVmRrZW1SSE9YbGFVekZ3WW01U2JBcGpiVEZzV2tkc2FHUkhWWGRJYUdOT1RXcEplRTFxUlRWTmFrRjRUbFJCZDFkb1kwNU5ha2w0VFdwRk5VMXFRWGxPVkVGM1YycEJRVTFHYTNkRmQxbElDa3R2V2tsNmFqQkRRVkZaU1V0dldrbDZhakJFUVZGalJGRm5RVVZMWlUxdmFWZHVWM0V2Vkd0NmExSXdRbWhxYTNKNlUwOU9NeTlpVmt0U1VqWmlZVVlLWVVGRlZFUTFSMlZqZFRKSmFUSkdhRFExWWtneFJVRnRiRmhyUm1NeWIxaFpSREZqUkU5NmJFTjNhMVJQYmpkRU9XRlBRMEZWVVhkblowWkJUVUUwUndwQk1WVmtSSGRGUWk5M1VVVkJkMGxJWjBSQlZFSm5UbFpJVTFWRlJFUkJTMEpuWjNKQ1owVkdRbEZqUkVGNlFXUkNaMDVXU0ZFMFJVWm5VVlU0U2pad0NuVk5PVVp2VmpsR2VHZHBXR2xRTm1oTFNGWlJjR2xCZDBoM1dVUldVakJxUWtKbmQwWnZRVlV6T1ZCd2VqRlphMFZhWWpWeFRtcHdTMFpYYVhocE5Ga0tXa1E0ZDBoM1dVUldVakJTUVZGSUwwSkNWWGRGTkVWU1dXNUtjRmxYTlVGYVIxWnZXVmN4YkdOcE5XcGlNakIzVEVGWlMwdDNXVUpDUVVkRWRucEJRZ3BCVVZGbFlVaFNNR05JVFRaTWVUbHVZVmhTYjJSWFNYVlpNamwwVERKNGRsb3liSFZNTWpsb1pGaFNiMDFKUjBwQ1oyOXlRbWRGUlVGa1dqVkJaMUZEQ2tKSWMwVmxVVUl6UVVoVlFUTlVNSGRoYzJKSVJWUktha2RTTkdOdFYyTXpRWEZLUzFoeWFtVlFTek12YURSd2VXZERPSEEzYnpSQlFVRkhSa3hCV2prS1VYZEJRVUpCVFVGU2FrSkZRV2xCYVc1VVZ6aFhhbFZNTDJWVWJVSnBVbEpqYW5vek1FZDNNMWRRUTNKMU1sRXlNV05OT0RCVWNHbzBVVWxuVTJkblZ3cDNjMVo2Vm1jNWNHVjFTSFJJZDBWQmRXbFRPRlZZYWt0blQyUlBRbTVuYWxWWlp5ODFhVlYzUTJkWlNVdHZXa2w2YWpCRlFYZE5SR0ZSUVhkYVowbDRDa0ZMZVhkdFIyZDZjbTVEZWs4clRubHlSbWhLVUVJemFucFpOVVZsVVdaUFQxWllXR0pVZG1kWEwxY3JVblpJUmpack9UUlFNMmxhVHl0a2NVWk1WMm9LTDFGSmVFRk1UM1ZpVVZKWWRGSTFUMk5SV0c0NVZUbHVVRXhoZWt0dk5EWlFVMmxuY1hZeFlWaFRUMnhQWTJKU1ZreE9USGhEVldaVmRGQkJLMVl2VVFwNU1XaGpSbmM5UFFvdExTMHRMVVZPUkNCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2c9PSJ9fX19"
      }
    ]
  },
  "messageSignature": {
    "messageDigest": {
      "algorithm": "SHA2_256",
      "digest": "aOZWslHmfoNYvvhIOrDVHGYZ8+ehqfDnWDjUH/No9yg="
    },
    "signature": "MEUCIQDZMdW7ehuLiZoUM0BZHFkeGetqcB9YNCeSeOTidBXaEgIgIw121n2K4fmUC7rtqcVK2HwIvxZjfvuIzAkePMXLbE4="
  }
}
```
New Format:
```json
{
  "mediaType": "application/vnd.dev.sigstore.bundle+json;version=0.1",
  "verificationMaterial": {
    "x509CertificateChain": {
      "certificates": [
        {
          "rawBytes": "MIICoDCCAiWgAwIBAgIUWgawjOXEzeCMsttpLScshik+QkQwCgYIKoZIzj0EAwMwNzEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MR4wHAYDVQQDExVzaWdzdG9yZS1pbnRlcm1lZGlhdGUwHhcNMjIxMjE5MjAxNTAwWhcNMjIxMjE5MjAyNTAwWjAAMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKeMoiWnWq/TkzkR0BhjkrzSON3/bVKRR6baFaAETD5Gecu2Ii2Fh45bH1EAmlXkFc2oXYD1cDOzlCwkTOn7D9aOCAUQwggFAMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQU8J6puM9FoV9FxgiXiP6hKHVQpiAwHwYDVR0jBBgwFoAU39Ppz1YkEZb5qNjpKFWixi4YZD8wHwYDVR0RAQH/BBUwE4ERYnJpYW5AZGVoYW1lci5jb20wLAYKKwYBBAGDvzABAQQeaHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoMIGJBgorBgEEAdZ5AgQCBHsEeQB3AHUA3T0wasbHETJjGR4cmWc3AqJKXrjePK3/h4pygC8p7o4AAAGFLAZ9QwAABAMARjBEAiAinTW8WjUL/eTmBiRRcjz30Gw3WPCru2Q21cM80Tpj4QIgSggWwsVzVg9peuHtHwEAuiS8UXjKgOdOBngjUYg/5iUwCgYIKoZIzj0EAwMDaQAwZgIxAKywmGgzrnCzO+NyrFhJPB3jzY5EeQfOOVXXbTvgW/W+RvHF6k94P3iZO+dqFLWj/QIxALOubQRXtR5OcQXn9U9nPLazKo46PSigqv1aXSOlOcbRVLNLxCUfUtPA+V/Qy1hcFw=="
        },
        {
          "rawBytes": "MIICGjCCAaGgAwIBAgIUALnViVfnU0brJasmRkHrn/UnfaQwCgYIKoZIzj0EAwMwKjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0yMjA0MTMyMDA2MTVaFw0zMTEwMDUxMzU2NThaMDcxFTATBgNVBAoTDHNpZ3N0b3JlLmRldjEeMBwGA1UEAxMVc2lnc3RvcmUtaW50ZXJtZWRpYXRlMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAE8RVS/ysH+NOvuDZyPIZtilgUF9NlarYpAd9HP1vBBH1U5CV77LSS7s0ZiH4nE7Hv7ptS6LvvR/STk798LVgMzLlJ4HeIfF3tHSaexLcYpSASr1kS0N/RgBJz/9jWCiXno3sweTAOBgNVHQ8BAf8EBAMCAQYwEwYDVR0lBAwwCgYIKwYBBQUHAwMwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU39Ppz1YkEZb5qNjpKFWixi4YZD8wHwYDVR0jBBgwFoAUWMAeX5FFpWapesyQoZMi0CrFxfowCgYIKoZIzj0EAwMDZwAwZAIwPCsQK4DYiZYDPIaDi5HFKnfxXx6ASSVmERfsynYBiX2X6SJRnZU84/9DZdnFvvxmAjBOt6QpBlc4J/0DxvkTCqpclvziL6BCCPnjdlIB3Pu3BxsPmygUY7Ii2zbdCdliiow="
        },
        {
          "rawBytes": "MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMwKjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0yMTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3JlLmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxexX69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92jYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRYwB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQKsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCMWP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ"
        }
      ]
    },
    "tlogEntries": [
      {
        "logIndex": "9430952",
        "logId": {
          "keyId": "wNI9atQGlz+VWfO6LRygH4QUfY/8W4RFwiT5i5WRgB0="
        },
        "kindVersion": {
          "kind": "hashedrekord",
          "version": "0.0.1"
        },
        "integratedTime": "1671480901",
        "inclusionPromise": {
          "signedEntryTimestamp": "MEQCIAgWJ1fq2e9fi7LwZRzVYXFg0vFxW8zahdXIWntyMMNoAiAhaTaEJkwTLYd8qiz162u8zHETX7o5qbXK38aKd1Vmkw=="
        },
        "canonicalizedBody": "eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI2OGU2NTZiMjUxZTY3ZTgzNThiZWY4NDgzYWIwZDUxYzY2MTlmM2U3YTFhOWYwZTc1ODM4ZDQxZmYzNjhmNzI4In19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FVUNJUURaTWRXN2VodUxpWm9VTTBCWkhGa2VHZXRxY0I5WU5DZVNlT1RpZEJYYUVnSWdJdzEyMW4ySzRmbVVDN3J0cWNWSzJId0l2eFpqZnZ1SXpBa2VQTVhMYkU0PSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTnZSRU5EUVdsWFowRjNTVUpCWjBsVlYyZGhkMnBQV0VWNlpVTk5jM1IwY0V4VFkzTm9hV3NyVVd0UmQwTm5XVWxMYjFwSmVtb3dSVUYzVFhjS1RucEZWazFDVFVkQk1WVkZRMmhOVFdNeWJHNWpNMUoyWTIxVmRWcEhWakpOVWpSM1NFRlpSRlpSVVVSRmVGWjZZVmRrZW1SSE9YbGFVekZ3WW01U2JBcGpiVEZzV2tkc2FHUkhWWGRJYUdOT1RXcEplRTFxUlRWTmFrRjRUbFJCZDFkb1kwNU5ha2w0VFdwRk5VMXFRWGxPVkVGM1YycEJRVTFHYTNkRmQxbElDa3R2V2tsNmFqQkRRVkZaU1V0dldrbDZhakJFUVZGalJGRm5RVVZMWlUxdmFWZHVWM0V2Vkd0NmExSXdRbWhxYTNKNlUwOU9NeTlpVmt0U1VqWmlZVVlLWVVGRlZFUTFSMlZqZFRKSmFUSkdhRFExWWtneFJVRnRiRmhyUm1NeWIxaFpSREZqUkU5NmJFTjNhMVJQYmpkRU9XRlBRMEZWVVhkblowWkJUVUUwUndwQk1WVmtSSGRGUWk5M1VVVkJkMGxJWjBSQlZFSm5UbFpJVTFWRlJFUkJTMEpuWjNKQ1owVkdRbEZqUkVGNlFXUkNaMDVXU0ZFMFJVWm5VVlU0U2pad0NuVk5PVVp2VmpsR2VHZHBXR2xRTm1oTFNGWlJjR2xCZDBoM1dVUldVakJxUWtKbmQwWnZRVlV6T1ZCd2VqRlphMFZhWWpWeFRtcHdTMFpYYVhocE5Ga0tXa1E0ZDBoM1dVUldVakJTUVZGSUwwSkNWWGRGTkVWU1dXNUtjRmxYTlVGYVIxWnZXVmN4YkdOcE5XcGlNakIzVEVGWlMwdDNXVUpDUVVkRWRucEJRZ3BCVVZGbFlVaFNNR05JVFRaTWVUbHVZVmhTYjJSWFNYVlpNamwwVERKNGRsb3liSFZNTWpsb1pGaFNiMDFKUjBwQ1oyOXlRbWRGUlVGa1dqVkJaMUZEQ2tKSWMwVmxVVUl6UVVoVlFUTlVNSGRoYzJKSVJWUktha2RTTkdOdFYyTXpRWEZLUzFoeWFtVlFTek12YURSd2VXZERPSEEzYnpSQlFVRkhSa3hCV2prS1VYZEJRVUpCVFVGU2FrSkZRV2xCYVc1VVZ6aFhhbFZNTDJWVWJVSnBVbEpqYW5vek1FZDNNMWRRUTNKMU1sRXlNV05OT0RCVWNHbzBVVWxuVTJkblZ3cDNjMVo2Vm1jNWNHVjFTSFJJZDBWQmRXbFRPRlZZYWt0blQyUlBRbTVuYWxWWlp5ODFhVlYzUTJkWlNVdHZXa2w2YWpCRlFYZE5SR0ZSUVhkYVowbDRDa0ZMZVhkdFIyZDZjbTVEZWs4clRubHlSbWhLVUVJemFucFpOVVZsVVdaUFQxWllXR0pVZG1kWEwxY3JVblpJUmpack9UUlFNMmxhVHl0a2NVWk1WMm9LTDFGSmVFRk1UM1ZpVVZKWWRGSTFUMk5SV0c0NVZUbHVVRXhoZWt0dk5EWlFVMmxuY1hZeFlWaFRUMnhQWTJKU1ZreE9USGhEVldaVmRGQkJLMVl2VVFwNU1XaGpSbmM5UFFvdExTMHRMVVZPUkNCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2c9PSJ9fX19"
      }
    ]
  },
  "messageSignature": {
    "messageDigest": {
      "algorithm": "SHA2_256",
      "digest": "aOZWslHmfoNYvvhIOrDVHGYZ8+ehqfDnWDjUH/No9yg="
    },
    "signature": "MEUCIQDZMdW7ehuLiZoUM0BZHFkeGetqcB9YNCeSeOTidBXaEgIgIw121n2K4fmUC7rtqcVK2HwIvxZjfvuIzAkePMXLbE4="
  }
}
```

### CODE REVIEW

**Comment by feelepxyz** [comment]
@bdehamer will this mean we can't verify old bundles that we have created so far? Do we need to clear these from prod and start again or should we handle the old style bundles in sigstore-js?

**Comment by bdehamer** [comment]
@feelepxyz since this bundle change is not being accompanied w/ a corresponding bump to the bundle version number we don't have a good way support both this and the current format. We're going to have to just roll everything forward.

**Comment by feelepxyz** [comment]
@bdehamer makes sense, we'll need to coordinate using the new sigstore-js release across the CLI and the different npm services and the bundle migration.

**Review by feelepxyz — APPROVED** [review]
Appreciate all your work dealing with all this bundle churn!

**Review by feelepxyz — APPROVED** [review]

**Pull request merged**
